# Generated by Django 6.0.4 on 2026-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('opening_crawl', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'films',
            },
        ),
        migrations.CreateModel(
            name='DjangoCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('mass', models.CharField(blank=True, max_length=10, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='characters', to='infrastructure.djangofilm')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='DjangoPlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('climate', models.CharField(blank=True, max_length=100, null=True)),
                ('terrain', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=50, null=True)),
                ('gravity', models.CharField(blank=True, max_length=50, null=True)),
                ('diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='planets', to='infrastructure.djangofilm')),
            ],
            options={
                'db_table': 'planets',
            },
        ),
    ]
